### ISSUE TITLE
JS errors on donate page

### ISSUE THREAD

**Issue by bentoner** [effective-altruism-australia/donation_portal#101]

**Comment by bentoner** [comment]
![2019-04-08_074755](https://user-images.githubusercontent.com/4795/55690295-e1ee3600-59d2-11e9-8f92-fa98a6970b1c.png)

**Comment by andrewbird2** [comment]
![image](https://user-images.githubusercontent.com/24581001/59188309-06f05800-8b80-11e9-9467-af2f89fb9cde.png)
