### ISSUE TITLE
JS takes a second to load

### ISSUE THREAD

**Issue by andrewbird2** [effective-altruism-australia/donation_portal#4]
When you hit the website the page is blank for about a second while the JS loads.  

Perhaps a simple loading animation?

@tehpurpleman , what do you reckon?  I'm happy to have a go and send you a pull request.  If you don't think its an issue happy to drop it.

**Comment by bentoner** [comment]
go ahead. note you need to this on the drupal side of things

**Comment by andrewbird2** [comment]
Issues are currently being managed in an external google doc.
