### ISSUE TITLE
When receipts are sent, we currently CC the partner org.  Now there are multiple orgs.  Should we CC the full list?

### ISSUE THREAD

**Issue by andrewbird2** [effective-altruism-australia/donation_portal#56]

**Comment by bentoner** [comment]
In terms of privacy, I don't think we should do that. We should stop cc'ing the charity on all donations. (It would be a strange and potentially confusing distinction to cc the charity only when they are the partner earmarked.) We don't have a requirement to cc them anyway - we chose to do that for increased accountability.

**Comment by andrewbird2** [comment]
Sounds good!
