### ISSUE TITLE
Donation form: It's really unclear why Donate button is disabled if you don't select "One-Time" or "Monthly"

### ISSUE THREAD

**Issue by bentoner** [effective-altruism-australia/donation_portal#78]
Can we fix this by defaulting to One-Time?

Or can we provide some feedback as to what the issue is if you do click the disabled Donate button.

**Comment by bentoner** [comment]
Can we fix this by defaulting to One-Time?

Or can we provide some feedback as to what the issue is if you do click the disabled Donate button.

**Comment by andrewbird2** [comment]
Defaulting to one-time
