### ISSUE TITLE
Donation form: Accept AMEX

### ISSUE THREAD

**Issue by bentoner** [effective-altruism-australia/donation_portal#92]
It should just work once we've removed any blockers that we've put in place. We've enabled it with Pin.

Remind me to edit the FAQ after this is done (the fees are a bit different).

**Comment by andrewbird2** [comment]
Blockers removed.  What are the changes in fees?

**Comment by bentoner** [comment]
It's about the same (communicated to you on slack), so I don't see the need to change the FAQ - but you can if you think it best to do so.
