### ISSUE TITLE
Gift certificates

### ISSUE THREAD

**Issue by bentoner** [effective-altruism-australia/donation_portal#97]
Suggestion (via @norrishd): for gift donations it would be awesome if the email included a little PDF "gift certificate" with info on the charity & the impact of the donation (like from the impact calculator page generates).

This requires designing a template in HTML. You could start from https://github.com/effective-altruism-australia/donation_portal/blob/master/donation/templates/receipts/receipt_base.html (which, in the case of receipts, we then combine with their data via https://github.com/effective-altruism-australia/donation_portal/blob/master/donation/templates/receipts/receipt.html and convert to PDF).

(For impact, see #65 too.)

**Comment by norrishd** [comment]
I might be game to take this on, but i still have only the haziest of ideas how the server is set up or what the infrastructure is so probably need someone to talk me through it all/give access etc.

**Comment by bentoner** [comment]
@norrishd Sorry, I was unclear. The hard part of this is making an HTML template for the gift certificate. The rest is easy. I was trying to ask if you'd be able to help make a template then we could do the rest. The HTML file can be worked on without setting anything up. The deliverable would be files like the ones linked for receipts above. They should look good when converted to PDF using the command line tool `wkhtmltopdf`.

**Comment by norrishd** [comment]
Oh great! Sorry for being daft. I'd be happy to take this on then if no one gets to it sooner.

I'm away with very limited internet for Christmas though, so realistically might not be able to start till early in the new year.

**Comment by bentoner** [comment]
Okay cool. No rush.
